source "http://rubygems.org"

# Declare your gem's dependencies in dm_event.gemspec.
# Bundler will treat runtime dependencies like base dependencies, and
# development dependencies will be added by default to the :development group.
gemspec

# jquery-rails is used by the dummy application
gem "jquery-rails"

# Declare any dependencies that are still in development here instead of in
# your gemspec. These might include edge Rails or gems from your path or
# Git. Remember to move these dependencies to your gemspec before releasing
# your gem to rubygems.org.

# To use debugger
# gem 'debugger'

gem 'dm_ruby_extensions', :git => 'git://github.com/digitalmoksha/dm_ruby_extensions.git'
gem 'dm_core',            :git => 'git://github.com/digitalmoksha/dm_core.git'
gem 'dm_cms',             :git => 'git://github.com/digitalmoksha/dm_cms.git'
gem 'preferences',        :git => "git://github.com/digitalmoksha/preferences.git"
gem 'themes_for_rails',   :git => 'git://github.com/digitalmoksha/themes_for_rails.git'
gem 'aced_rails',         :git => 'git://github.com/digitalmoksha/aced_rails.git'

# To use debugger
gem 'debugger'
gem 'ruby_gntp'
