#!/usr/bin/env rake
require 'rubygems'
require 'rake'
require 'rake/testtask'
require 'rspec/core/rake_task'

begin
  require 'bundler/setup'
rescue LoadError
  puts 'You must `gem install bundler` and `bundle install` to run rake tasks'
end

# APP_RAKEFILE = File.expand_path("../spec/dummy/Rakefile", __FILE__)
# load 'rails/tasks/engine.rake'

Bundler::GemHelper.install_tasks

# require 'rspec/core'
# require 'rspec/core/rake_task'
require 'moksha_cms/testing_support/common_rake'

RSpec::Core::RakeTask.new

# desc "Run all specs in spec directory (excluding plugin specs)"
# RSpec::Core::RakeTask.new(:spec => 'app:db:test:prepare')

task default: :spec

desc "Generates a dummy app for testing"
task :test_app do
  ENV['LIB_NAME'] = 'dm_lms'
  Rake::Task['common:test_app'].invoke
end
